<!DOCTYPE NEWSPAPER [
        <!ELEMENT NEWSPAPER (ARTICLE+)>
        <!ELEMENT ARTICLE (HEADLINE,BYLINE,LEAD,BODY,NOTES)>
        <!ELEMENT HEADLINE (#PCDATA)>
        <!ELEMENT BYLINE (#PCDATA)>
        <!ELEMENT LEAD (#PCDATA)>
        <!ELEMENT BODY (#PCDATA)>
        <!ELEMENT NOTES (#PCDATA)>
        <!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
        <!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
        <!ATTLIST ARTICLE DATE CDATA #IMPLIED>
        <!ATTLIST ARTICLE EDITION CDATA #IMPLIED>
        ]>
 <NEWSPAPER>
    <ARTICLE AUTHOR="123" EDITION="aaa">
        <HEADLINE>123</HEADLINE>
        <BYLINE>123</BYLINE>
        <LEAD>123</LEAD>
        <BODY>123</BODY>
        <NOTES>123</NOTES>
    </ARTICLE>
</NEWSPAPER>